language: java
jdk:
  - openjdk11
branches:
  only:
    - master
    - coverity_scan
env:
  global:
    - secure: "U+RrKhdImhnpzPM/m/fC14B96MCI6gfPzClhakmgVVRNHYe5YDc2+xNwdY2QEM5k6HY2Jm3u84l/RlAY8A8qijKlwMqXpXE9bnMl02ONpdknN1lX1vds5OhEGPCoXvjMTN7RpR/0/5UBIDH+mpq2hN+FjLa1yO8FhvrrcNiLQEv03abe4uJZqRQhoL73oxjJDh80hqFQ2PHfsWz8Mkgw1vEs3WGE5UDWM/N5XE15bJdoq4Lx7/1+dgc6CjoRQCEHt2P5rI4NHckts+8Dplf8Ae+gLCI1dQm/cNSxBYmSZF+KXRLZWPvnNSGqh0BYFeEUIRmDQyl1Yi4t5MQqSvXz0oF0HX+EOUUVo7amo0swpevRQdrTutUU5NZvM0Xsizb5oxcZqe51NIQPIUySlwDJLhgZVtMcXNqKhRb1IhOl6qNwz6e8+FVOCTejaDSIjNq6pRVF4v/kbSWaaGykqbtuZmSLAHufAYA5tH4l96wFm1BzJSL/XFnscHAJzyM++v+nm8fIR7jHL7KnBoUAFpnpqe1R9azGQiPi3IWcgp9tUbd1rNULHEFHpuMIyjJ4Ew6TCvurVtj74I4HHu/5LjgCB9Nrj6QzASNVvoaJ0spnc+nyX//w9Yj1u8qFDHU3AE22JX41ikUrvuiTsRlIBp+w2YP59rULzBEVf3Ekn/9ly3s="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "wultra/powerauth-webflow"
      description: "Build submitted via Travis CI"
    notification_email: roman.strobl@wultra.com
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
